apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-build-agent
  namespace: azure-build-agent
spec:
  selector:
    matchLabels:
      app: azure-build-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-build-agent
    spec:
      containers:
        - name: azure-build-agent
          image: >-
            image-registry.openshift-image-registry.svc:5000/azure-build-agent/azure-build-agent:latest
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
      serviceAccount: azure-build-sa
      serviceAccountName: azure-build-sa
