apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-build-agent
spec:
  selector:
    matchLabels:
      app: azure-build-agent
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app: azure-build-agent
    spec:
      containers:
        - name: azure-build-agent
          image: azure-build-agent:latest
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: azdevops
          - secretRef:
              name: azproxy
              optional: true
          ports:
          - containerPort: 8080
          securityContext:
            runAsUser: 1001
      serviceAccount: azure-build-sa
      serviceAccountName: azure-build-sa
